### ISSUE TITLE
Allow optional list of files to be apart of the package

### ISSUE THREAD

**Issue by dvorakd** [campoy/jsonenums#17]
I've found it useful to access the `_TypeNameToValue` map in the generated code from other places in my package (probably not best practice), but if I remove the generated file and rerun `go generate` again it will cause an `undeclared name` error.

Perhaps it would be useful to allow a list of files as arguments to `jsonenums` to limit what it parses as apart of the package, i.e. `jsonenums -type myType ...files`  Then we could use a line such as:

`//go:generate jsonenums -type=myType $GOFILE`

in the file that contains the type declaration.

**Comment by campoy** [comment]
Thanks for your contribution, but this tool is just a sample.
I will not add extra features, just fixes on the current functionality.
