### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by oscarzhou** [campoy/jsonenums#29]
Sorry, I really do not know how to use this? I put the `//go:generate jsonenums -type=OnlineType` in  the file. Then I input `go generate`. It doesn't work. Is there anyone who can teach me?

**Comment by dzintars** [comment]
Assuming this is already solved, will leave comment for others.
You have 2 options:
1) You can use `jsonenums -type=OnlineType` right from the package directory.
2) You can place `//go:generate jsonenums -type=OnlineType` right before ` type OnlineType int` and then to execute `go generate`

Be sure you do `go get github.com/campoy/jsonenums` to get this tool.
Be sure you set the type like
```go
const (
  myConstantOne **OnlineType** = iota
  myConstantTwo
)
```
